### ISSUE TITLE
docker container error

### ISSUE THREAD

**Issue by Famku** [ofkm/arcane#107]
Hi

I set the correct GID and get this error:

Entrypoint: Running as root. Setting up user and permissions...
Entrypoint: Using PUID=1000, PGID=1000, DOCKER_GID=999
Entrypoint: Group with GID 1000 already exists: arcane
Entrypoint: Updating docker group from GID 998 to 999...
groupmod: GID '999' already exists

**Comment by adamshand** [comment]
I'm getting a similar thing.

```
ponga 28s
❯ dcu
[+] Running 14/14
 ✔ arcane Pulled                                                                                                                     17.8s
   ✔ f18232174bc9 Already exists                                                                                                      0.0s
   ✔ 63786652eaff Pull complete                                                                                                      13.6s
   ✔ 0c2b42acd277 Pull complete                                                                                                      13.7s
   ✔ 4509b69886a5 Pull complete                                                                                                      13.7s
   ✔ fa1c9bfe383b Pull complete                                                                                                      13.9s
   ✔ f8f8663d3d96 Pull complete                                                                                                      13.9s
   ✔ f0fc5ea8e9e8 Pull complete                                                                                                      14.0s
   ✔ f4704b57d887 Pull complete                                                                                                      14.0s
   ✔ 5eb982ae6ab7 Pull complete                                                                                                      14.2s
   ✔ 9a1a3f77efb8 Pull complete                                                                                                      14.3s
   ✔ a44f9ec4c18c Pull complete                                                                                                      14.3s
   ✔ 964aaa4e1119 Pull complete                                                                                                      14.4s
   ✔ 5d7d32b704f7 Pull complete                                                                                                      15.3s
[+] Running 2/2
 ✔ Network arcane_default  Created                                                                                                    0.0s
 ✔ Container arcane        Started                                                                                                    1.1s
arcane  | 2025-05-05T09:19:36.908647302Z Entrypoint: Running as root. Setting up user and permissions...
arcane  | 2025-05-05T09:19:36.908687536Z Entrypoint: Using PUID=999, PGID=999, DOCKER_GID=991
arcane  | 2025-05-05T09:19:36.911644957Z Entrypoint: Group with GID 999 already exists: ping
arcane  | 2025-05-05T09:19:36.913183182Z Entrypoint: Updating docker group from GID 998 to 991...
arcane  | 2025-05-05T09:19:36.953518035Z Entrypoint: Creating user arcane with UID 999...
arcane  | 2025-05-05T09:19:36.954072991Z adduser: user 'arcane' in use
arcane exited with code 0
arcane  | 2025-05-05T09:19:37.603821373Z Entrypoint: Running as root. Setting up user and permissions...
arcane  | 2025-05-05T09:19:37.603901979Z Entrypoint: Using PUID=999, PGID=999, DOCKER_GID=991
arcane  | 2025-05-05T09:19:37.609172671Z Entrypoint: Group with GID 999 already exists: ping
arcane  | 2025-05-05T09:19:37.609189829Z Entrypoint: Creating user arcane with UID 999...
arcane  | 2025-05-05T09:19:37.606864415Z adduser: user 'arcane' in use
arcane exited with code 0
arcane  | 2025-05-05T09:19:38.205963262Z Entrypoint: Running as root. Setting up user and permissions...
arcane  | 2025-05-05T09:19:38.206286792Z Entrypoint: Using PUID=999, PGID=999, DOCKER_GID=991
arcane  | 2025-05-05T09:19:38.207105011Z Entrypoint: Group with GID 999 already exists: ping
arcane  | 2025-05-05T09:19:38.208516341Z Entrypoint: Creating user arcane with UID 999...
arcane  | 2025-05-05T09:19:38.208927038Z adduser: user 'arcane' in use
arcane exited with code 1
arcane exited with code 1
^C
```

**Comment by kmendell** [comment]
Whats does your compose file look like?

**Comment by moookino** [comment]
I have same error with example from docs and only updated values for PUID, PGID, DOCKER_GID, nothing changes otherwise

**Comment by kmendell** [comment]
@moookino as a test can you use `user: root` in your compose file to see if it launches successfully?

**Comment by kmendell** [comment]
This should be fixed in https://github.com/ofkm/arcane/commit/a3ec54a058548a66ae9e637cdd6e34228c5e995b and will be available in the next release. 

You can try the development image to make sure this works for you as well until the next release: `ghcr.io/ofkm/arcane:development`

**Comment by 123mariachi123** [comment]
@kmendell FYI adding "-user=root" instead of PUID and PGID works.

The development version works as well. But only if i stick with 1000:1000. 
If i create a dedicated arcane user and group 1006:1006 i still get the above error. Maybe i am misunderstanding the concept though (in my case, 1000 is already assigned to a user of another app)
```
Entrypoint: Running as root. Setting up user and permissions...
Entrypoint: Using PUID=1006, PGID=1006, DOCKER_GID=996
Entrypoint: Creating group arcane with GID 1006...
addgroup: group 'arcane' in use
```

**Comment by kmendell** [comment]
@123mariachi123 Can you try the development image now? :) I think i fixed it. Appreciate the patience on this as well.

**Comment by moookino** [comment]
also worked for me with user root. So should we stick with root for now?

**Comment by kmendell** [comment]
If you are fine with running as root yeah, In theory the rootless stuff should work as long as the permissions exsist on the docker socket, but root of course is easier.

**Comment by 123mariachi123** [comment]
> [@123mariachi123](https://github.com/123mariachi123) Can you try the development image now? :) I think i fixed it. Appreciate the patience on this as well.

Sure I can test it a bit later when I’m back at my pc

**Comment by 123mariachi123** [comment]
@kmendell unfortunately, no change in the latest development. Unless i do something wrong 😄 . I deleted the existing image and pulled a fresh one using this compose

```yaml
services:
  arcane:
    image: ghcr.io/ofkm/arcane:development
    container_name: arcane
    ports:
      - '3333:3000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/arcane/app/data:/app/data
    environment:
      - PUID=1006
      - PGID=1006
      - DOCKER_GID=996 # getent group docker | cut -d: -f3
    restart: unless-stopped
```

and made sure the /opt/arcane/app/data belongs to 1006:1006.

And this is the log
```
Entrypoint: Running as root. Setting up user and permissions...
Entrypoint: Using PUID=1006, PGID=1006, DOCKER_GID=996
Entrypoint: Group arcane already exists with correct GID 1006
Entrypoint: Creating user arcane with UID 1006...
adduser: user 'arcane' in use
```

Switching back to PUID and PGID 1000 and it works again.

**Comment by XanderD99** [comment]
Hi, I encountered this issue as well. 

For me it worked to change my GID of my local docker group. It was 999 but this conflicted with the ping group of the applications docker container so it failed to start up. After changing my docker group to 998 everything was fine. 

Perhaps this should be something that is checked as well?

**Comment by adamshand** [comment]
It's working now for me.  I had changed the default values of PUID/GUID so they didn't conflict with an existing user.

Changing them back to 1000 fixed the problem I was having.

**Comment by kmendell** [comment]
> Hi, I encountered this issue as well.
> 
> For me it worked to change my GID of my local docker group. It was 999 but this conflicted with the ping group of the applications docker container so it failed to start up. After changing my docker group to 998 everything was fine.
> 
> Perhaps this should be something that is checked as well?

Ill look into that, do the docker functions work? If the GID dont match technially it shouldnt work from the testing i did.

**Comment by Famku** [comment]
the issue still exist for me with v0.5

**Comment by kmendell** [comment]
Can you try runing it with `user: root` in the compose file?

**Comment by Famku** [comment]
I already did, and tested it on another host, the same problem

Running as root. Setting up user and permissions...
Entrypoint: Using PUID=1000, PGID=1000, DOCKER_GID=999
Entrypoint: Group with GID 1000 already exists: arcane
Entrypoint: Updating docker group from GID 998 to 999...
groupmod: GID '999' already exists

**Comment by kmendell** [comment]
@Famku  Can you try `ghcr.io/ofkm/arcane:development` I just removed the ping group and the iputils package from the conatiner so that should work now.

**Comment by Famku** [comment]
It works!

**Comment by kmendell** [comment]
Awesome, That fix will be included in the next release.

**Comment by kmendell** [comment]
The DOCKER_GID=999 issue has been fixed in `v0.6.0`. Still working on the UID/GID Fix.

**Comment by varadins** [comment]
1 services:                                                                                                                   
 2   arcane:                                                                                                                   
 3     image: ghcr.io/ofkm/arcane:latest                                                                                       
 4     container_name: arcane                                                                                                  
 5     user: root                                                                                                              
 6     ports:                                                                                                                  
 7       - '5070:3000'                                                                                                         
 8     volumes:                                                                                                                
 9       - /var/run/docker.sock:/var/run/docker.sock                                                                           
10       - arcane-data:/app/data                                                                                               
11     environment:                                                                                                            
12       - APP_ENV=development                                                                                                 
13       - DOCKER_GID=1000                                                                                                     
14       - PUBLIC_SESSION_SECRET=[REDACTED]                                                  
15       - PUBLIC_ALLOW_INSECURE_COOKIES=true                                                                                  
16     restart: unless-stopped                                                                                                 
17                                                                                                                             
18 volumes:                                                                                                                    
19   arcane-data:                                                                                                              
20     driver: local 

Results in 

Entrypoint: Running as root. Setting up user and permissions...
Entrypoint: Using PUID=1000, PGID=1000, DOCKER_GID=1000
Entrypoint: Group with GID 1000 already exists: arcane
Entrypoint: Updating docker group from GID 998 to 1000...
groupmod: GID '1000' already exists

**Comment by kmendell** [comment]
GID 1000 is the user in the container, is GID 1000 actually what your docker GID is on the host?

**Comment by varadins** [comment]
> GID 1000 is the user in the container, is GID 1000 actually what your docker GID is on the host?

docker@docker1:~/docker/arcane$ getent group docker | cut -d: -f3
1000

**Comment by kmendell** [comment]
This should be fixed in `0.7.1`

**Comment by varadins** [comment]
Repulled everything.
Same error in production or development 

What can I share to help?

**Comment by kmendell** [comment]
What version were you on? Did it say 0.7.1? The build takes awhile to build and publish after i create a release.

**Comment by varadins** [comment]
Confirmed:  v0.7.1

docker@docker1:~/docker/arcane$ getent group docker | cut -d: -f3
1000

2025-05-10T03:56:32.511581083Z Entrypoint: Setting up user and permissions...
2025-05-10T03:56:32.511664887Z Entrypoint: Using PUID=1000, PGID=1000, DOCKER_GID=1000
2025-05-10T03:56:32.512994013Z Entrypoint: Group with GID 1000 already exists: arcane
2025-05-10T03:56:32.513600323Z Entrypoint: Creating docker group with GID 1000...
2025-05-10T03:56:32.514085204Z addgroup: gid '1000' in use

services:
  arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: arcane
    user: root
    ports:
      - '5071:3000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - arcane-data:/app/data
    environment:
      - APP_ENV=development
      - DOCKER_GID=1000
      - PUBLIC_SESSION_SECRET=[REDACTED]
      - PUBLIC_ALLOW_INSECURE_COOKIES=true
    restart: unless-stopped

volumes:
  arcane-data:
    driver: local

**Comment by kmendell** [comment]
@varadins Can you try this image?: `ghcr.io/ofkm/arcane:uid2000`

**Comment by varadins** [comment]
That image worked!

2025-05-10T05:33:56.207497151Z Entrypoint: Setting up user and permissions...
2025-05-10T05:33:56.207534185Z Entrypoint: Using PUID=2000, PGID=2000, DOCKER_GID=1000
2025-05-10T05:33:56.208099210Z Entrypoint: Creating group arcane with GID 2000...
2025-05-10T05:33:56.223090115Z Entrypoint: Creating docker group with GID 1000...
2025-05-10T05:33:56.227090700Z Entrypoint: Creating user arcane with UID 2000 and GID 2000...
2025-05-10T05:33:56.247638142Z Entrypoint: Adding arcane to the docker group...
2025-05-10T05:33:56.254165554Z Docker socket accessible at /var/run/docker.sock (GID: 1000)
2025-05-10T05:33:56.254177416Z Entrypoint: Ensuring data directory exists and setting ownership...
2025-05-10T05:33:56.255517821Z Entrypoint: Setup complete. Executing command as user arcane (UID: 2000, GID: 2000)...
2025-05-10T05:33:56.529761310Z No users found. Creating default admin user...
2025-05-10T05:33:56.736409343Z Stacks directory initialized: data/stacks
2025-05-10T05:33:56.736772239Z Auto-update is disabled in settings
2025-05-10T05:33:57.691389895Z Generating new encryption key...
2025-05-10T05:33:57.757351106Z Default admin user created successfully

**Comment by Xboarder56** [comment]
I'm seeing this issue as well on latest:

Edit: I tried on the image ghcr.io/ofkm/arcane:uid2000 and also same issue.

```
arcane  | Entrypoint: Setting up user and permissions...
arcane  | Entrypoint: Using PUID=1000, PGID=100, DOCKER_GID=998
arcane  | Entrypoint: Group with GID 100 already exists: users
arcane  | Entrypoint: Creating docker group with GID 998...
arcane  | Entrypoint: User with UID 1000 already exists: arcane
arcane  | Entrypoint: Adding arcane to the docker group...
arcane  | Docker socket GID (0) doesn't match configured docker group GID.
arcane  | Updating docker group to match socket GID: 0
arcane  | addgroup: gid '0' in use
```

Compose:

```
 arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: arcane
    restart: unless-stopped
    user: "root"
    ports:
      - 3000:3000
    environment:
      - APP_ENV=production
      - PUBLIC_SESSION_SECRET=${ARCANE_SESSION_SECRET}
      - PUID=1000
      - PGID=100
    networks:
      - traefik-portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /share/Docker/dockergui/Arcane:/app/data
```

**Comment by kmendell** [comment]
@Xboarder56 Try removing user: root and see if it works, That may not be needed anymore, but either way that is an issue and I will look at it.

**Comment by Xboarder56** [comment]
Current test config with error block, same UID/GID work fine on portainer:

Compose:
```
  arcane:
    #image: ghcr.io/ofkm/arcane:latest
    image: ghcr.io/ofkm/arcane:uid2000
    container_name: arcane
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - PUBLIC_SESSION_SECRET=${ARCANE_SESSION_SECRET}
      - PUID=1000
      - PGID=100
    networks:
      - traefik-portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /share/Docker/dockergui/Arcane:/app/data
```

Docker Logs:
```
arcane  | Entrypoint: Setting up user and permissions...
arcane  | Entrypoint: Using PUID=1000, PGID=100, DOCKER_GID=998
arcane  | Entrypoint: Group with GID 100 already exists: users
arcane  | Entrypoint: Creating docker group with GID 998...
arcane  | Entrypoint: User with UID 1000 already exists: arcane
arcane  | Entrypoint: Adding arcane to the docker group...
arcane  | Docker socket GID (0) doesn't match configured docker group GID.
arcane  | Updating docker group to match socket GID: 0
arcane  | addgroup: gid '0' in use
```

**Comment by varadins** [comment]
ghcr.io/ofkm/arcane:uid2000 worked for me, but now I'm lagging behind on updates.  

Has this been resolved in production?

**Comment by Soljanka** [comment]
I do not want to create a new issue since this seems to be resolved but I am just not sure what to do. I just tried to deploy arcane for the first time using the template from the [quick start guide](https://arcane.ofkm.dev/docs/getting-started/quickstart) and ran into a similar issue. This is the template:

```
services:
  arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: arcane
    ports:
      - '3000:3000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - arcane-data:/app/data
    environment:
      - APP_ENV=production # Required
      - PUBLIC_SESSION_SECRET=mystrongsecret # Generate: openssl rand -base64 32
      # Optional: Match your host user for permissions
      - PUID=2000
      - PGID=2000
      # Optional: Set if Docker access fails
      # - DOCKER_GID=998
      # Optional: For local HTTP testing only
      # - PUBLIC_ALLOW_INSECURE_COOKIES=true
    restart: unless-stopped

volumes:
  arcane-data:
    driver: local
```


Yet my container does not start:
```
arcane  | Entrypoint: Setting up user and permissions...
arcane  | Entrypoint: Using PUID=2000, PGID=2000, DOCKER_GID=998
arcane  | Entrypoint: Group with GID 2000 already exists: arcane
arcane  | Entrypoint: Creating docker group with GID 998...
arcane  | Entrypoint: User with UID 2000 already exists: arcane
arcane  | Entrypoint: Adding arcane to the docker group...
```

**Comment by kmendell** [comment]
> I do not want to create a new issue since this seems to be resolved but I am just not sure what to do. I just tried to deploy arcane for the first time using the template from the [quick start guide](https://arcane.ofkm.dev/docs/getting-started/quickstart) and ran into a similar issue. This is the template:
> 
> ```
> services:
>   arcane:
>     image: ghcr.io/ofkm/arcane:latest
>     container_name: arcane
>     ports:
>       - '3000:3000'
>     volumes:
>       - /var/run/docker.sock:/var/run/docker.sock
>       - arcane-data:/app/data
>     environment:
>       - APP_ENV=production # Required
>       - PUBLIC_SESSION_SECRET=mystrongsecret # Generate: openssl rand -base64 32
>       # Optional: Match your host user for permissions
>       - PUID=2000
>       - PGID=2000
>       # Optional: Set if Docker access fails
>       # - DOCKER_GID=998
>       # Optional: For local HTTP testing only
>       # - PUBLIC_ALLOW_INSECURE_COOKIES=true
>     restart: unless-stopped
> 
> volumes:
>   arcane-data:
>     driver: local
> ```
> 
> Yet my container does not start:
> 
> ```
> arcane  | Entrypoint: Setting up user and permissions...
> arcane  | Entrypoint: Using PUID=2000, PGID=2000, DOCKER_GID=998
> arcane  | Entrypoint: Group with GID 2000 already exists: arcane
> arcane  | Entrypoint: Creating docker group with GID 998...
> arcane  | Entrypoint: User with UID 2000 already exists: arcane
> arcane  | Entrypoint: Adding arcane to the docker group...
> ```

Try manuall passing the Docker GID to the conatiner and see if it starts.

**Comment by Soljanka** [comment]
Thanks for your fast reply. Do you mean to uncomment `# - DOCKER_GID=998` ? Because I had no luck either with the following env

```
    environment:
      - APP_ENV=production # Required
      - PUBLIC_SESSION_SECRET=mystrongsecret # Generate: openssl rand -base64 32
      # Optional: Match your host user for permissions
      - PUID=2000
      - PGID=2000
      # Optional: Set if Docker access fails
      - DOCKER_GID=998
      # Optional: For local HTTP testing only
      # - PUBLIC_ALLOW_INSECURE_COOKIES=true
```
I got basically the same output

```
arcane  | Entrypoint: Setting up user and permissions...
arcane  | Entrypoint: Using PUID=2000, PGID=2000, DOCKER_GID=998
arcane  | Entrypoint: Group with GID 2000 already exists: arcane
arcane  | Entrypoint: Creating docker group with GID 998...
arcane  | Entrypoint: User with UID 2000 already exists: arcane
arcane  | Entrypoint: Adding arcane to the docker group...
arcane  | Docker socket GID (0) doesn't match configured docker group GID.
arcane  | Updating docker group to match socket GID: 0
arcane  | addgroup: gid '0' in use
```

**Comment by weedy** [comment]
I can start 0.7.0 with user:root, but it can't connect to docker.
Everything newer doesn't work. No combination of...
```
    user: root
    environment:
      - PUID=0
      - PGID=0
      - DOCKER_GID=0
```
```
    user: arcane
    environment:
      - PUID=0
      - PGID=0
      - DOCKER_GID=0
```
```
    user: root
    environment:
      - PUID=1001
      - PGID=1000
      - DOCKER_GID=0
```
```
    user: arcane
    environment:
      - PUID=1001
      - PGID=1000
      - DOCKER_GID=0
```
```
    user: root
    environment:
      - PUID=1001
      - PGID=1000
      - DOCKER_GID=1000
```
```
    user: arcane
    environment:
      - PUID=1001
      - PGID=1000
      - DOCKER_GID=1000
```
```
    environment:
      - PUID=9999
      - PGID=9999
      - DOCKER_GID=0
```
works.


My understanding would be I want 1001/1000 and my NAS runs docker with 0.
Which fails.

**Comment by kmendell** [comment]
@weedy  the docker gid should be the Group ID of the docker socket not `0`

**Comment by weedy** [comment]
```
]# stat  /var/run/docker.sock
  File: '/var/run/docker.sock'
  Size: 0               Blocks: 0          IO Block: 4096   socket
Device: 14h/20d Inode: 2068970     Links: 1
Access: (0660/srw-rw----)  Uid: (    0/    root)   Gid: (    0/    root)

```

**Comment by weedy** [comment]
Stable will not work.
I made preview install properly https://github.com/ofkm/arcane/issues/304#issuecomment-3146686830
