### ISSUE TITLE
🐞 Bug:  Dashboard doesn't have stats anymore

### ISSUE THREAD

**Issue by weedy** [ofkm/arcane#517]
### Bug Description

See screenshot.
Stats are gone after the start of your rework

### Steps To Reproduce

Install `:next`
Use Arcane

### Expected Behavior

Working Dashboard

### Actual Behavior

Broken Dashboard

### Screenshots

<img width="1161" height="774" alt="Image" src="https://github.com/user-attachments/assets/05297a9a-9bf5-443b-a0f1-00a642f958c2" />

### Arcane Version

next

### Operating System

Windows

### Browser

Edge

### Docker Version

27

**Comment by kmendell** [comment]
This is definitely something on your server, i just pulled the latest next image as of a few minutes ago and they are working for me, Can you share logs of the container?  

<img width="2415" height="599" alt="Image" src="https://github.com/user-attachments/assets/7528888b-8f18-48c5-8208-b36f034ce9af" />

**Comment by weedy** [comment]
How would you like the logs?

**Comment by weedy** [comment]
<img width="1546" height="1851" alt="Image" src="https://github.com/user-attachments/assets/74100a05-6339-4da3-8afc-d147761d7aab" />

```
Sep 19 20:44:29.888 INF Incoming request request.time=2025-09-20T00:44:29.887Z request.method=GET request.host=thevault.local:3042 request.path=/api/settings request.query="" request.params=map[] request.route=/api/settings request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:44:29.888Z response.latency=519.719µs response.status=200 response.length=1424
Sep 19 20:44:29.895 INF Incoming request request.time=2025-09-20T00:44:29.889Z request.method=GET request.host=thevault.local:3042 request.path=/api/environments/0/containers request.query="pagination%5Bpage%5D=1&pagination%5Blimit%5D=20&sort%5Bcolumn%5D=created&sort%5Bdirection%5D=desc" request.params=map[id:0] request.route=/api/environments/:id/containers request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:44:29.895Z response.latency=6.537956ms response.status=200 response.length=30517
Sep 19 20:44:29.897 INF Incoming request request.time=2025-09-20T00:44:29.891Z request.method=GET request.host=thevault.local:3042 request.path=/api/environments/0/containers/counts request.query="" request.params=map[id:0] request.route=/api/environments/:id/containers/counts request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:44:29.897Z response.latency=5.998623ms response.status=200 response.length=90
Sep 19 20:49:01.143 INF Incoming request request.time=2025-09-20T00:49:01.142Z request.method=GET request.host=thevault.local:3042 request.path=/dashboard request.query="" request.params=map[] request.route="" request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:49:01.143Z response.latency=43.951µs response.status=200 response.length=1516
Sep 19 20:49:01.926 INF Incoming request request.time=2025-09-20T00:49:01.926Z request.method=GET request.host=thevault.local:3042 request.path=/_app/immutable/entry/start.D_SRoumy.js request.query="" request.params=map[] request.route="" request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:49:01.926Z response.latency=45.066µs response.status=200 response.length=83
Sep 19 20:49:01.947 INF Incoming request request.time=2025-09-20T00:49:01.947Z request.method=GET request.host=thevault.local:3042 request.path=/_app/immutable/chunks/DRHoMzKi.js request.query="" request.params=map[] request.route="" request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:49:01.947Z response.latency=140.048µs response.status=200 response.length=32105
Sep 19 20:49:01.948 INF Incoming request request.time=2025-09-20T00:49:01.948Z request.method=GET request.host=thevault.local:3042 request.path=/_app/immutable/chunks/C70wp3QT.js request.query="" request.params=map[] request.route="" request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:49:01.948Z response.latency=144.57µs response.status=200 response.length=31521
Sep 19 20:49:01.951 INF Incoming request request.time=2025-09-20T00:49:01.951Z request.method=GET request.host=thevault.local:3042 request.path=/_app/immutable/chunks/D0iwhpLH.js request.query="" request.params=map[] request.route="" request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:49:01.951Z response.latency=39.506µs response.status=200 response.length=504
Sep 19 20:49:01.953 INF Incoming request request.time=2025-09-20T00:49:01.952Z request.method=GET request.host=thevault.local:3042 request.path=/_app/immutable/entry/app.D9YrFbpn.js request.query="" request.params=map[] request.route="" request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:49:01.952Z response.latency=120.279µs response.status=200 response.length=19769
Sep 19 20:49:01.955 INF Incoming request request.time=2025-09-20T00:49:01.955Z request.method=GET request.host=thevault.local:3042 request.path=/_app/immutable/chunks/D9Z9MdNV.js request.query="" request.params=map[] request.route="" request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:49:01.955Z response.latency=44.868µs response.status=200 response.length=1234
Sep 19 20:49:01.957 INF Incoming request request.time=2025-09-20T00:49:01.956Z request.method=GET request.host=thevault.local:3042 request.path=/_app/immutable/chunks/C37WzBb4.js request.query="" request.params=map[] request.route="" request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:49:01.957Z response.latency=121.595µs response.status=200 response.length=36015
Sep 19 20:49:01.959 INF Incoming request request.time=2025-09-20T00:49:01.959Z request.method=GET request.host=thevault.local:3042 request.path=/_app/immutable/chunks/DsnmJJEf.js request.query="" request.params=map[] request.route="" request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:49:01.959Z response.latency=33.619µs response.status=200 response.length=66
Sep 19 20:49:01.964 INF Incoming request request.time=2025-09-20T00:49:01.964Z request.method=GET request.host=thevault.local:3042 request.path=/_app/immutable/chunks/ClshroTG.js request.query="" request.params=map[] request.route="" request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:49:01.964Z response.latency=44.466µs response.status=200 response.length=779
Sep 19 20:49:01.966 INF Incoming request request.time=2025-09-20T00:49:01.966Z request.method=GET request.host=thevault.local:3042 request.path=/_app/immutable/chunks/CV0tVQ3P.js request.query="" request.params=map[] request.route="" request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:49:01.966Z response.latency=36.006µs response.status=200 response.length=436
Sep 19 20:49:01.970 INF Incoming request request.time=2025-09-20T00:49:01.969Z request.method=GET request.host=thevault.local:3042 request.path=/_app/immutable/chunks/qKSirsWo.js request.query="" request.params=map[] request.route="" request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:49:01.970Z response.latency=39.465µs response.status=200 response.length=302
Sep 19 20:49:01.970 INF Incoming request request.time=2025-09-20T00:49:01.970Z request.method=GET request.host=thevault.local:3042 request.path=/_app/immutable/chunks/BfvwY1VQ.js request.query="" request.params=map[] request.route="" request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:49:01.970Z response.latency=29.775µs response.status=200 response.length=2746
Sep 19 20:49:01.972 INF Incoming request request.time=2025-09-20T00:49:01.972Z request.method=GET request.host=thevault.local:3042 request.path=/img/arcane.png request.query="" request.params=map[] request.route="" request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:49:01.972Z response.latency=143.572µs response.status=200 response.length=68324
Sep 19 20:49:02.287 INF Incoming request request.time=2025-09-20T00:49:02.286Z request.method=GET request.host=thevault.local:3042 request.path=/api/auth/me request.query="" request.params=map[] request.route=/api/auth/me request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:49:02.287Z response.latency=1.035124ms response.status=200 response.length=162
Sep 19 20:49:02.291 INF Incoming request request.time=2025-09-20T00:49:02.291Z request.method=GET request.host=thevault.local:3042 request.path=/api/version request.query="current=1.1.0" request.params=map[] request.route=/api/version request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:49:02.291Z response.latency=22.213µs response.status=200 response.length=140
Sep 19 20:49:02.291 INF Incoming request request.time=2025-09-20T00:49:02.290Z request.method=GET request.host=thevault.local:3042 request.path=/api/settings request.query="" request.params=map[] request.route=/api/settings request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:49:02.291Z response.latency=437.214µs response.status=200 response.length=1424
Sep 19 20:49:02.322 INF Incoming request request.time=2025-09-20T00:49:02.322Z request.method=GET request.host=thevault.local:3042 request.path=/api/environments request.query="pagination%5Bpage%5D=1&pagination%5Blimit%5D=1000" request.params=map[] request.route=/api/environments request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:49:02.322Z response.latency=506.103µs response.status=200 response.length=106
Sep 19 20:49:02.339 INF Incoming request request.time=2025-09-20T00:49:02.333Z request.method=GET request.host=thevault.local:3042 request.path=/api/environments/0/containers request.query="pagination%5Bpage%5D=1&pagination%5Blimit%5D=5&sort%5Bcolumn%5D=created&sort%5Bdirection%5D=desc" request.params=map[id:0] request.route=/api/environments/:id/containers request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:49:02.339Z response.latency=6.297659ms response.status=200 response.length=13239
Sep 19 20:49:02.375 INF Incoming request request.time=2025-09-20T00:49:02.347Z request.method=GET request.host=thevault.local:3042 request.path=/api/environments/0/images request.query="pagination%5Bpage%5D=1&pagination%5Blimit%5D=5&sort%5Bcolumn%5D=size&sort%5Bdirection%5D=desc" request.params=map[id:0] request.route=/api/environments/:id/images request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:49:02.375Z response.latency=27.752231ms response.status=200 response.length=7289
Sep 19 20:49:02.387 INF Incoming request request.time=2025-09-20T00:49:02.382Z request.method=GET request.host=thevault.local:3042 request.path=/api/environments/0/containers/counts request.query="" request.params=map[id:0] request.route=/api/environments/:id/containers/counts request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:49:02.387Z response.latency=5.970922ms response.status=200 response.length=90
Sep 19 20:49:02.395 INF Incoming request request.time=2025-09-20T00:49:02.395Z request.method=GET request.host=thevault.local:3042 request.path=/api/settings request.query="" request.params=map[] request.route=/api/settings request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:49:02.395Z response.latency=468.329µs response.status=200 response.length=1424
Sep 19 20:49:02.447 INF Incoming request request.time=2025-09-20T00:49:02.394Z request.method=GET request.host=thevault.local:3042 request.path=/api/system/docker/info request.query="" request.params=map[] request.route=/api/system/docker/info request.ip=10.0.0.147 request.referer=http://thevault.local:3042/dashboard request.length=0 response.time=2025-09-20T00:49:02.447Z response.latency=52.534688ms response.status=200 response.length=552
```

**Comment by kmendell** [comment]
Do you see anything in the browser console about the web socket failing to connect?

**Comment by weedy** [comment]
Nothing in console except that version check

**Comment by Osvaldo-Net** [comment]
Despues de actualizar a la ultima version tengo un problema parecido,  ajuste en teoría nginx para eso sin embargo no recibo data 
<img width="1919" height="804" alt="Image" src="https://github.com/user-attachments/assets/4761b237-b1e6-4dff-92b0-9fbf5d0e20eb" />

   location / {
    proxy_pass http://127.0.0.1:9443;
    proxy_http_version 1.1;


    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Authorization $http_authorization;
    proxy_set_header Cookie $http_cookie;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
 }

**Comment by Lokowitz** [comment]
Same problem for me with version 1.2.0

**Comment by phil3741** [comment]
Same problem here after upgrade to 1.2.0. Raspberry Pi 4b

**Comment by jsross33** [comment]
I have the same problem, but only on one of my systems. A desktop running Linux Mint 22.2 x86_64. The exact same compose file works just fine on my three raspberry pi 4's.

EDIT: after reading kmendell's response below, a proxy does seem to be my issue. Logging in from the localhost and everything seems to be working as intended. (info) The proxy in use is HAproxy on pfSense.

**Comment by kmendell** [comment]
The dashboard and logs use websockets so your reverse proxy would need to make sure to allow them, I can not reproduce this on my servers, i have my main one and then a remote one thats in oracle cloud both of which the dashboard works on no issues. Caddy is the reverse proxy i use. 

If you can proivde any info on how your reverse proxy is setup that may be helpful as well.

**Comment by weedy** [comment]
I'm not using a proxy.
Just whatever NAT happens for the docker bridge.

**Comment by phil3741** [comment]
I use caddy too and checked for any breaking changes before updating to 1.2.0. Since there are none specified, previously working reverse proxy settings I left unchanged:


```
# ----------  Arcane  ----------
https://arcane.XYZ.com {
        reverse_proxy * http://arcane:3552
}
```

**Comment by kmendell** [comment]
Do the dashboard stats not load for the local environment AND remote envs'? or just one or the other? I cant reproduce it no matter what i try.

**Comment by Osvaldo-Net** [comment]
> ¿Las estadísticas del panel no se cargan para el entorno local ni para los entornos remotos? ¿O solo para uno? No puedo reproducirlo por mucho que lo intente.

En mi caso, donde uso un mini pc y el entorno es local no cargan las estadísticas, antes de la última actualización se visualizaban sin novedad.

**Comment by jetlifedza** [comment]
> Do the dashboard stats not load for the local environment AND remote envs'? or just one or the other? I cant reproduce it no matter what i try.

I can only confirm for local env. I used 1.1.0 before on a fresh install and all was good and now fresh 1.2.0 and everything works well and same as before except the dashboard.

other docker container that for example use docker.sock like gethomepage work btw, so it worked before and all other. this has to be some bug from 1.2.0

**Comment by LilTrublMakr** [comment]
If you are trying to connect to an agent and view the stats, update the agent container as well. The agent stats worked fine after updating.

**Comment by phil3741** [comment]
The error still persists in 1.2.1. In my setup I only use local environment and do not connect to any remotes.

During testing, I noticed the missing dashboard stats only appear through the reverse proxy, which in my case is Caddy with the following setting, so it is something in combination with the reverse proxy:

```
# ----------  Arcane  ----------
https://arcane.XYZ.com {
        reverse_proxy * http://arcane:3552
}
```

From localhost via http, the stats show correctly. I am not sure what else needs to be configured in order to make the reverse proxy work properly. 


During start of the container the following error appears:
arcane  | Sep 23 05:54:43.704 ERR analytics heartbeat failed error="request failed with status: 429"
arcane  | Sep 23 05:54:43.705 ERR Error executing task function name=analytics-heartbeat error="analytics heartbeat request failed: request failed with status: 429"


Here is a full log from starting the container, to loading the page (without working stats):
```
Attaching to arcane
arcane  | Entrypoint: Setting up user and permissions...
arcane  | Entrypoint: Using PUID=1000, PGID=1000, DOCKER_GID=998
arcane  | Entrypoint: User arcane already exists with UID 1000
arcane  | usermod: no changes
arcane  | Entrypoint: Docker socket found with GID 991
arcane  | Entrypoint: Docker socket configured (GID: 991)
arcane  | Entrypoint: Setting up data directory...
arcane  | Entrypoint: Projects path used for GID detection: /app/data/projects/nextcloud (uid:1000 gid:1000)
arcane  | Entrypoint: Setup complete. Starting as arcane (UID: 1000, GID: 1000)
arcane  | Sep 23 06:17:34.757 INF No .env file found, using environment variables
arcane  | Sep 23 06:17:34.762 INF Database schema is up to date
arcane  | Sep 23 06:17:34.762 INF Database initialized successfully
arcane  | Sep 23 06:17:34.765 INF Ensuring default settings are initialized
arcane  | Sep 23 06:17:34.772 INF Default settings initialized successfully
arcane  | Sep 23 06:17:34.772 WRN CORS: No origins specified for production - defaulting to https://localhost
arcane  | Sep 23 06:17:34.773 INF Performing initial Docker image synchronization with the database
arcane  | Sep 23 06:17:34.941 INF Initial Docker image synchronization complete
arcane  | Sep 23 06:17:34.942 WRN Users already exist, skipping default admin creation
arcane  | Sep 23 06:17:34.947 INF auto-update disabled or polling disabled; job not registered autoUpdate=false pollingEnabled=true
arcane  | Sep 23 06:17:34.948 INF registering image polling job interval=1h0m0s
arcane  | Sep 23 06:17:34.949 INF Job registered successfully name=image-polling
arcane  | Sep 23 06:17:34.949 INF registering analytics heartbeat job jobName=analytics-heartbeat interval=24h0m0s endpoint=https://analytics.arcane.ofkm.dev/heartbeat
arcane  | Sep 23 06:17:34.949 INF Job registered successfully name=analytics-heartbeat
arcane  | Sep 23 06:17:34.949 INF Registering event cleanup job jobName=EventCleanup
arcane  | Sep 23 06:17:34.949 INF Job registered successfully name=EventCleanup
arcane  | Sep 23 06:17:34.949 INF Event cleanup job registered successfully jobName=EventCleanup interval=6h retention=36h
arcane  | Sep 23 06:17:34.949 INF Filesystem watcher job registered
arcane  | Sep 23 06:17:34.949 INF Starting scheduler goroutine
arcane  | Sep 23 06:17:34.949 INF Starting job scheduler
arcane  | Sep 23 06:17:34.949 INF Starting server port=3552
arcane  | Sep 23 06:17:34.950 INF Job starting name=analytics-heartbeat id=98a83fdd-c8dc-4238-982c-0e63831f2844
arcane  | Sep 23 06:17:34.955 INF sending analytics heartbeat jobName=analytics-heartbeat
arcane  | Sep 23 06:17:35.548 INF Filesystem watcher started path=data/projects
arcane  | Sep 23 06:17:35.549 INF Filesystem watcher started path=data/templates
arcane  | Sep 23 06:17:35.549 INF Filesystem watcher started for projects directory path=data/projects
arcane  | Sep 23 06:17:35.549 INF Filesystem watcher started for templates directory path=data/templates
arcane  | Sep 23 06:17:36.746 ERR analytics heartbeat failed error="request failed with status: 429"
arcane  | Sep 23 06:17:36.746 ERR Error executing task function name=analytics-heartbeat error="analytics heartbeat request failed: request failed with status: 429"
arcane  | Sep 23 06:17:36.746 INF Job finished successfully name=analytics-heartbeat id=98a83fdd-c8dc-4238-982c-0e63831f2844
arcane  | Sep 23 06:17:39.266 INF Incoming request request.time=2025-09-23T06:17:39.265Z request.method=GET request.host=arcane.XYZ.com request.path=/dashboard request.query="" request.params=map[] request.route="" request.ip=172.18.0.1 request.referer=https://arcane.XYZ.com/ request.length=0 response.time=2025-09-23T06:17:39.266Z response.latency=378.331µs response.status=200 response.length=1512
arcane  | Sep 23 06:17:39.363 INF Incoming request request.time=2025-09-23T06:17:39.363Z request.method=GET request.host=arcane.XYZ.com request.path=/_app/immutable/chunks/Bu1fQcF6.js request.query="" request.params=map[] request.route="" request.ip=172.18.0.1 request.referer="" request.length=0 response.time=2025-09-23T06:17:39.363Z response.latency=88.499µs response.status=200 response.length=67
arcane  | Sep 23 06:17:39.365 INF Incoming request request.time=2025-09-23T06:17:39.365Z request.method=GET request.host=arcane.XYZ.com request.path=/_app/immutable/chunks/Cj36Kzha.js request.query="" request.params=map[] request.route="" request.ip=172.18.0.1 request.referer="" request.length=0 response.time=2025-09-23T06:17:39.365Z response.latency=107.111µs response.status=200 response.length=1075
arcane  | Sep 23 06:17:39.388 INF Incoming request request.time=2025-09-23T06:17:39.388Z request.method=GET request.host=arcane.XYZ.com request.path=/_app/immutable/assets/index.CV-KWLNP.css request.query="" request.params=map[] request.route="" request.ip=172.18.0.1 request.referer=https://arcane.XYZ.com/dashboard request.length=0 response.time=2025-09-23T06:17:39.388Z response.latency=92.278µs response.status=200 response.length=289
arcane  | Sep 23 06:17:39.408 INF Incoming request request.time=2025-09-23T06:17:39.408Z request.method=GET request.host=arcane.XYZ.com request.path=/_app/immutable/chunks/CiimcqDU.js request.query="" request.params=map[] request.route="" request.ip=172.18.0.1 request.referer="" request.length=0 response.time=2025-09-23T06:17:39.408Z response.latency=112.722µs response.status=200 response.length=153
arcane  | Sep 23 06:17:39.408 INF Incoming request request.time=2025-09-23T06:17:39.408Z request.method=GET request.host=arcane.XYZ.com request.path=/_app/immutable/assets/0.D-VXfbtc.css request.query="" request.params=map[] request.route="" request.ip=172.18.0.1 request.referer=https://arcane.XYZ.com/dashboard request.length=0 response.time=2025-09-23T06:17:39.408Z response.latency=599.737µs response.status=200 response.length=15182
arcane  | Sep 23 06:17:39.410 INF Incoming request request.time=2025-09-23T06:17:39.410Z request.method=GET request.host=arcane.XYZ.com request.path=/_app/immutable/chunks/CzBSUQ9P.js request.query="" request.params=map[] request.route="" request.ip=172.18.0.1 request.referer="" request.length=0 response.time=2025-09-23T06:17:39.410Z response.latency=696.255µs response.status=200 response.length=230
arcane  | Sep 23 06:17:39.504 INF Incoming request request.time=2025-09-23T06:17:39.503Z request.method=GET request.host=arcane.XYZ.com request.path=/api/settings request.query="" request.params=map[] request.route=/api/settings request.ip=172.18.0.1 request.referer=https://arcane.XYZ.com/dashboard request.length=0 response.time=2025-09-23T06:17:39.504Z response.latency=649.978µs response.status=200 response.length=1081
arcane  | Sep 23 06:17:39.505 INF Incoming request request.time=2025-09-23T06:17:39.503Z request.method=GET request.host=arcane.XYZ.com request.path=/api/auth/me request.query="" request.params=map[] request.route=/api/auth/me request.ip=172.18.0.1 request.referer=https://arcane.XYZ.com/dashboard request.length=0 response.time=2025-09-23T06:17:39.505Z response.latency=2.260764ms response.status=200 response.length=162
arcane  | Sep 23 06:17:39.531 INF Incoming request request.time=2025-09-23T06:17:39.530Z request.method=GET request.host=arcane.XYZ.com request.path=/api/environments request.query="pagination%5Bpage%5D=1&pagination%5Blimit%5D=1000" request.params=map[] request.route=/api/environments request.ip=172.18.0.1 request.referer=https://arcane.XYZ.com/dashboard request.length=0 response.time=2025-09-23T06:17:39.531Z response.latency=1.552805ms response.status=200 response.length=106
arcane  | Sep 23 06:17:39.568 INF Incoming request request.time=2025-09-23T06:17:39.552Z request.method=GET request.host=arcane.XYZ.com request.path=/api/environments/0/containers request.query="pagination%5Bpage%5D=1&pagination%5Blimit%5D=5&sort%5Bcolumn%5D=created&sort%5Bdirection%5D=desc" request.params=map[id:0] request.route=/api/environments/:id/containers request.ip=172.18.0.1 request.referer=https://arcane.XYZ.com/dashboard request.length=0 response.time=2025-09-23T06:17:39.568Z response.latency=15.666168ms response.status=200 response.length=11826
arcane  | Sep 23 06:17:39.746 INF Incoming request request.time=2025-09-23T06:17:39.600Z request.method=GET request.host=arcane.XYZ.com request.path=/api/environments/0/images request.query="pagination%5Bpage%5D=1&pagination%5Blimit%5D=5&sort%5Bcolumn%5D=size&sort%5Bdirection%5D=desc" request.params=map[id:0] request.route=/api/environments/:id/images request.ip=172.18.0.1 request.referer=https://arcane.XYZ.com/dashboard request.length=0 response.time=2025-09-23T06:17:39.746Z response.latency=145.859388ms response.status=200 response.length=5290
arcane  | Sep 23 06:17:39.787 INF Incoming request request.time=2025-09-23T06:17:39.772Z request.method=GET request.host=arcane.XYZ.com request.path=/api/environments/0/containers/counts request.query="" request.params=map[id:0] request.route=/api/environments/:id/containers/counts request.ip=172.18.0.1 request.referer=https://arcane.XYZ.com/dashboard request.length=0 response.time=2025-09-23T06:17:39.786Z response.latency=14.459897ms response.status=200 response.length=91
arcane  | Sep 23 06:17:39.811 INF Incoming request request.time=2025-09-23T06:17:39.811Z request.method=GET request.host=arcane.XYZ.com request.path=/api/settings request.query="" request.params=map[] request.route=/api/settings request.ip=172.18.0.1 request.referer=https://arcane.XYZ.com/dashboard request.length=0 response.time=2025-09-23T06:17:39.811Z response.latency=537.793µs response.status=200 response.length=1081
arcane  | Sep 23 06:17:39.814 INF Incoming request request.time=2025-09-23T06:17:39.504Z request.method=GET request.host=arcane.XYZ.com request.path=/api/version request.query="current=1.2.1" request.params=map[] request.route=/api/version request.ip=172.18.0.1 request.referer=https://arcane.XYZ.com/dashboard request.length=0 response.time=2025-09-23T06:17:39.814Z response.latency=310.398926ms response.status=200 response.length=140
arcane  | Sep 23 06:17:39.878 INF Incoming request request.time=2025-09-23T06:17:39.811Z request.method=GET request.host=arcane.XYZ.com request.path=/api/environments/0/docker/info request.query="" request.params=map[id:0] request.route=/api/environments/:id/docker/info request.ip=172.18.0.1 request.referer=https://arcane.XYZ.com/dashboard request.length=0 response.time=2025-09-23T06:17:39.878Z response.latency=67.361199ms response.status=200 response.length=558
arcane  | Sep 23 06:17:39.950 INF Incoming request request.time=2025-09-23T06:17:39.950Z request.method=GET request.host=arcane.XYZ.com request.path=/img/arcane.svg request.query="" request.params=map[] request.route="" request.ip=172.18.0.1 request.referer=https://arcane.XYZ.com/dashboard request.length=0 response.time=2025-09-23T06:17:39.950Z response.latency=87.259µs response.status=200 response.length=1533
arcane  | Sep 23 06:17:40.024 INF Incoming request request.time=2025-09-23T06:17:40.024Z request.method=GET request.host=arcane.XYZ.com request.path=/img/profile.jpg request.query="" request.params=map[] request.route="" request.ip=172.18.0.1 request.referer=https://arcane.XYZ.com/dashboard request.length=0 response.time=2025-09-23T06:17:40.024Z response.latency=456.534µs response.status=200 response.length=9156

```

The web console only shows version info, no errors:

<img width="1204" height="230" alt="Image" src="https://github.com/user-attachments/assets/7e0c573a-67ac-41a6-8cf2-0383dc24ce38" />


When switching to v1.1.0, the dashboard immediately works again


I also tried adding 

{
                header_up Host {host}
                header_up X-Forwarded-Host {host}
                header_up X-Forwarded-Proto {scheme}
                header_up X-Forwarded-For {remote_host}
        }

to the reverse proxy, with no effect.

the URL I use for the reverse proxy is definitely set as environment variable - APP_URL="https://arcane.XYZ.com"



EDIT:
Upon reading the logs I noticed the probable candidate:
arcane  | Sep 23 06:17:34.772 WRN CORS: No origins specified for production - defaulting to https://localhost

although I have set the "APP_URL" Environment variable in the docker compose file? ( The same log is showing in the working v1.1.0)

I also tried multiple times to wipe my config and data and start a new onboarding process. No effect.

**Comment by patillacode** [comment]
I also have the same issue.

I just upgraded and came to look if anyone else had the same issue 😅 

**Version: 1.2.1** 

My stats are also not loading and I cannot see logs of any container (which makes sense since this feels like a socket issue)

I can see the following errors in the browser console:

```shell
Firefox can’t establish a connection to the server at wss://mydomain.com/api/environments/0/containers/9991c85a963c1fd6b0e7f56e592f7edbdb6615bab785750242bf7d1f528503e4/logs/ws?follow=true&tail=100&timestamps=true&format=json&batched=true. [BhxzfRqW.js:1:2847](https://mydomain.com/_app/immutable/chunks/BhxzfRqW.js)
```

```shell 
WebSocket log stream error: 
error { target: WebSocket, isTrusted: true, srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }
```

And the following in the network tab:

<img width="538" height="219" alt="Image" src="https://github.com/user-attachments/assets/f37a7dc2-1315-4edb-93ef-47f78e452406" />

<img width="1942" height="82" alt="Image" src="https://github.com/user-attachments/assets/a54480dc-df8e-40f9-b7c8-58a440f18261" />

Nothing in the logs though.

```
arcane  | Entrypoint: Setting up user and permissions...
arcane  | Entrypoint: Using PUID=1000, PGID=1000, DOCKER_GID=998
arcane  | Entrypoint: User arcane already exists with UID 1000
arcane  | usermod: no changes
arcane  | Entrypoint: Docker socket found with GID 998
arcane  | Entrypoint: Docker socket configured (GID: 998)
arcane  | Entrypoint: Setting up data directory...
arcane  | Entrypoint: Projects path used for GID detection: /app/data/projects/ligaconquis-staging (uid:1000 gid:1000)
arcane  | Entrypoint: Setup complete. Starting as arcane (UID: 1000, GID: 1000)
arcane  | Sep 23 12:48:37.190 INF No .env file found, using environment variables
arcane  | Sep 23 12:48:37.191 INF Database schema is up to date
arcane  | Sep 23 12:48:37.191 INF Database initialized successfully
arcane  | Sep 23 12:48:37.192 INF Ensuring default settings are initialized
arcane  | Sep 23 12:48:37.193 INF Default settings initialized successfully
arcane  | Sep 23 12:48:37.193 INF Performing initial Docker image synchronization with the database
arcane  | Sep 23 12:48:37.549 INF Initial Docker image synchronization complete
arcane  | Sep 23 12:48:37.550 WRN Users already exist, skipping default admin creation
arcane  | Sep 23 12:48:37.551 INF auto-update disabled or polling disabled; job not registered autoUpdate=false pollingEnabled=true
arcane  | Sep 23 12:48:37.552 INF registering image polling job interval=24h0m0s
arcane  | Sep 23 12:48:37.552 INF Job registered successfully name=image-polling
arcane  | Sep 23 12:48:37.552 INF registering analytics heartbeat job jobName=analytics-heartbeat interval=24h0m0s endpoint=https://analytics.arcane.ofkm.dev/heartbeat
arcane  | Sep 23 12:48:37.552 INF Job registered successfully name=analytics-heartbeat
arcane  | Sep 23 12:48:37.552 INF Registering event cleanup job jobName=EventCleanup
arcane  | Sep 23 12:48:37.552 INF Job registered successfully name=EventCleanup
arcane  | Sep 23 12:48:37.552 INF Event cleanup job registered successfully jobName=EventCleanup interval=6h retention=36h
arcane  | Sep 23 12:48:37.552 INF Filesystem watcher job registered
arcane  | Sep 23 12:48:37.552 INF Starting scheduler goroutine
arcane  | Sep 23 12:48:37.557 INF Starting job scheduler
arcane  | Sep 23 12:48:37.552 INF Starting server port=3552
arcane  | Sep 23 12:48:37.558 INF Job starting name=analytics-heartbeat id=d8337e32-32a9-4fee-80a3-65e49c28327d
arcane  | Sep 23 12:48:37.568 INF sending analytics heartbeat jobName=analytics-heartbeat
arcane  | Sep 23 12:48:38.145 INF Filesystem watcher started path=data/projects
arcane  | Sep 23 12:48:38.145 INF Filesystem watcher started path=data/templates
arcane  | Sep 23 12:48:38.145 INF Filesystem watcher started for projects directory path=data/projects
arcane  | Sep 23 12:48:38.145 INF Filesystem watcher started for templates directory path=data/templates
arcane  | Sep 23 12:48:39.481 ERR analytics heartbeat failed error="request failed with status: 429"
arcane  | Sep 23 12:48:39.482 ERR Error executing task function name=analytics-heartbeat error="analytics heartbeat request failed: request failed with status: 429"
arcane  | Sep 23 12:48:39.482 INF Job finished successfully name=analytics-heartbeat id=d8337e32-32a9-4fee-80a3-65e49c28327d
arcane  | Sep 23 12:49:10.502 INF Incoming request request.time=2025-09-23T12:49:10.501Z request.method=GET request.host=127.0.0.1:3552 request.path=/dashboard request.query="" request.params=map[] request.route="" request.ip=192.168.1.1 request.referer="" request.length=0 response.time=2025-09-23T12:49:10.501Z response.latency=381.784µs response.status=200 response.length=1512
```

**Comment by dswd** [comment]
Not sure if this is related or not:

I have a setup using Caddy and Authelia. I ran into the same issue as reported here with the stats missing and never loading. In the network tab I was seeing repeated WS connection attempts getting 101 "switching protocol" but nothing more. In Authelia however I saw that those requests were rejected for reasons I don't fully understand.

However, adding a whitelist entry to Caddy circumventing Authelia for /api/system/stats/ws and /api/environments/0/stats/ws did the trick for me.

**Comment by kmendell** [comment]
Hmm. Im wondering if my cors middleware isnt working for websockets, but if it wasnt id feel like id be able to reproduce it. That being said i dont really have strict rules in my homelab for internal services. Still this is not making sense to me at all.

**Comment by lotharzenger** [comment]
should it not be sth that changed from 1.1 to 1.2? as everybody had it working with 1.1

**Comment by kmendell** [comment]
> should it not be sth that changed from 1.1 to 1.2? as everybody had it working with 1.1

The change from 1.1 to 1.2 was the use of websockets, Ill be the first to admit that im not a expert with websockets however it is more effeicnet then a GET request every second with SSE events, based on my analysis. What confuses me is how i cant reproduce it, thats why this is stumping me a bit.

**Comment by dswd** [comment]
Okay, looking at my logs I found one thing that could be a clue: The network tab shows repeated requests only for wss://.../api/environments/0/stats/ws. Authelia however shows repeated requests for both https://.../api/environments/0/stats/ws with proper credentials and https://.../api/system/stats/ws without credentials. It is as if there was a redirect that somehow swallows the cookie header that Authelia uses.

**Comment by skoeber** [comment]
I have the same issue with arcane behind NginxProxyManager. I observe requests like this one, that will never be answered:

`GET wss://arcane.mydomain.de/api/environments/0/stats/ws`

Can I provide any further information that would help?

**Comment by kmendell** [comment]
Ill have a test image read for testing in a second for whoever would like to test, this may be a back and forth troubleshooting thing. But the branch i started making changes to is https://github.com/ofkm/arcane/tree/fix/websockets. Again im not a expert so if people have ideas feel free to make a PR against that branch 

The image to test is : `ghcr.io/ofkm/arcane:websockets`

**Comment by dswd** [comment]
I just tried it and there is no difference in behavior.
Looking at the error message and scanning through your code, could it be that the backend is somehow connecting to itself? That would be an obvious reason why it doesn't work.

**Comment by kmendell** [comment]
It does work as i cant reproduce it, in my prod env and testing one, The environment handler will "proxy" the request if its goes to a remote env, but besides taht it should just be a simple endpoint. what is shown for the connection to taht endpoint? does it say its connected?

**Comment by skoeber** [comment]
In my case there's no difference, too.

NPM has an option for WebSocket support. That is checked. I tried several settings, nothing changed. Unfortunately I'm no expert in this WebSocket and proxy topic. Is there anything else I can test?

**Comment by kmendell** [comment]
Can you pull it again and see if there are any changes now?

**Comment by skoeber** [comment]
With the latest pull of the websockets image it's now working!

Thanks for the great work!

**Comment by dswd** [comment]
Yes, I can also confirm that this code works.

**Comment by kmendell** [comment]
Holy i didnt actually think i fixed it... :D Well yay! I need to do some cleanup but ill merge it later today, Thank you for testing and thank you for the help troubleshooting it!

**Comment by weedy** [comment]
oi, what do you mean closed as working. 
I haven't tested shi... oh it works.

Thanks Kyle.

**Comment by phil3741** [comment]
Thank you for the quick debugging! Really appreciate the project, and I hope my logs somehow helped in fixing this

**Comment by patillacode** [comment]
_Sorry to comment on a closed issue but it seemed to work for most you and not for me.
Please let me know if I should open a new issue instead._

I upgraded to version [v1.2.2](https://github.com/ofkm/arcane/releases/tag/v1.2.2) after reading your comments and I still don't see stats nor logs.
I am still where I was in my [original comment](https://github.com/ofkm/arcane/issues/517#issuecomment-3323895055).

<img width="1925" height="560" alt="Image" src="https://github.com/user-attachments/assets/9bbd5666-16f5-414b-a291-b0f565268dd3" />

<img width="1936" height="65" alt="Image" src="https://github.com/user-attachments/assets/0e5e260d-5e1e-4cfe-a0a3-b9f915d27125" />
<img width="1287" height="27" alt="Image" src="https://github.com/user-attachments/assets/19460088-1ec0-4806-97f4-b85fa3fcec20" />

I am running arcane via docker compose:
```docker
services:
  arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: arcane
    ports:
      - '3552:3552'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./arcane-data:/app/data
      - /home/dvitto/projects:/app/data/projects
    environment:
      - APP_URL=https://arcane.mydomain.com
      - PUID=1000
      - PGID=1000
      - ENCRYPTION_KEY=my_super_encryption_key
      - JWT_SECRET=my_super_jwt_secret
    restart: unless-stopped

volumes:
  arcane-data:
```

I am behind a custom domain handled via nginx, sharing my nginx config in case I missed something but it was working in the previous version [v1.1.0](https://github.com/ofkm/arcane/releases/tag/v1.1.0)

```shell
server {
   listen 80;
   server_name arcane.mydomain.com;
   # Redirection from HTTP site to HTTPS
   return 301 https://$host$request_uri;

}

server {
        listen 443 ssl http2;

        ssl_certificate        /etc/letsencrypt/live/arcane.mydomain.com/fullchain.pem;
        ssl_certificate_key    /etc/letsencrypt/live/arcane.mydomain.com/privkey.pem;

        server_name arcane.mydomain.com;

        add_header X-Frame-Options "*";
        add_header X-Gank-Debug "debug";
        location / {
                add_header X-Robots-Tag "noindex, nofollow";
                proxy_pass http://127.0.0.1:3552;
                proxy_set_header X-Real-IP $remote_addr;
        }
        access_log /var/log/nginx/arcane-access.log;
        error_log /var/log/nginx/arcane-error.log debug;
}
```


Any ideas? did you fellas do something besides upgrade?

Thanks!

**Comment by jetlifedza** [comment]
> _Sorry to comment on a closed issue but it seemed to work for most you and not for me. Please let me know if I should open a new issue instead._
> 
> I upgraded to version [v1.2.2](https://github.com/ofkm/arcane/releases/tag/v1.2.2) after reading your comments and I still don't see stats nor logs. I am still where I was in my [original comment](https://github.com/ofkm/arcane/issues/517#issuecomment-3323895055).
> 
> <img alt="Image" width="1925" height="560" src="https://private-user-images.githubusercontent.com/10074977/493931951-9bbd5666-16f5-414b-a291-b0f565268dd3.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg4MDgzMjksIm5iZiI6MTc1ODgwODAyOSwicGF0aCI6Ii8xMDA3NDk3Ny80OTM5MzE5NTEtOWJiZDU2NjYtMTZmNS00MTRiLWEyOTEtYjBmNTY1MjY4ZGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTI1VDEzNDcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxOTQyMzczZmJkOTc5Mzk3ZjExNGRmYWU2MTIxZDUwNTA5NjUyNjYxZjE2YzdiYTkxYzIyNTY1MmQ3NDc3OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gamBuuiFlPyVp5fOn8lowUt0XJEfnIvAZJ_k9-U-EVM"> <img alt="Image" width="1936" height="65" src="https://private-user-images.githubusercontent.com/10074977/493931226-0e5e260d-5e1e-4cfe-a0a3-b9f915d27125.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg4MDgzMjksIm5iZiI6MTc1ODgwODAyOSwicGF0aCI6Ii8xMDA3NDk3Ny80OTM5MzEyMjYtMGU1ZTI2MGQtNWUxZS00Y2ZlLWEwYTMtYjlmOTE1ZDI3MTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTI1VDEzNDcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiYmI2MzJiNmRjNDJhMjc3ZmZkZGU1NmU3NmYxYTdmMGVhNWI5OTBjN2RhODA1ZDM2YzE1OTcyZjZkODVhODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.g6iOaGaBgk9zEtaXebAYEn20qMPbjqJpIYIHR-FjSC4"> <img alt="Image" width="1287" height="27" src="https://private-user-images.githubusercontent.com/10074977/493931227-19460088-1ec0-4806-97f4-b85fa3fcec20.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg4MDgzMjksIm5iZiI6MTc1ODgwODAyOSwicGF0aCI6Ii8xMDA3NDk3Ny80OTM5MzEyMjctMTk0NjAwODgtMWVjMC00ODA2LTk3ZjQtYjg1ZmEzZmNlYzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTI1VDEzNDcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0N2ZlODM0Y2ZjN2M4OWEwZjY2OGVmNzU2NTJkNzcyZGUzOTU3MDE2ZWMzODAxNTBmZGY5MGY1YmI5OWI3MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IYhPn6rSfyg2oT2rGfZ3Vb6wp7ywaaZE6zFLJI3h1lM">
> I am running arcane via docker compose:
> 
> ```
> services:
>   arcane:
>     image: ghcr.io/ofkm/arcane:latest
>     container_name: arcane
>     ports:
>       - '3552:3552'
>     volumes:
>       - /var/run/docker.sock:/var/run/docker.sock
>       - ./arcane-data:/app/data
>       - /home/dvitto/projects:/app/data/projects
>     environment:
>       - APP_URL=https://arcane.mydomain.com
>       - PUID=1000
>       - PGID=1000
>       - ENCRYPTION_KEY=my_super_encryption_key
>       - JWT_SECRET=my_super_jwt_secret
>     restart: unless-stopped
> 
> volumes:
>   arcane-data:
> ```
> 
> I am behind a custom domain handled via nginx, sharing my nginx config in case I missed something but it was working in the previous version [v1.1.0](https://github.com/ofkm/arcane/releases/tag/v1.1.0)
> 
> server {
>    listen 80;
>    server_name arcane.mydomain.com;
>    # Redirection from HTTP site to HTTPS
>    return 301 https://$host$request_uri;
> 
> }
> 
> server {
>         listen 443 ssl http2;
> 
>         ssl_certificate        /etc/letsencrypt/live/arcane.mydomain.com/fullchain.pem;
>         ssl_certificate_key    /etc/letsencrypt/live/arcane.mydomain.com/privkey.pem;
> 
>         server_name arcane.mydomain.com;
> 
>         add_header X-Frame-Options "*";
>         add_header X-Gank-Debug "debug";
>         location / {
>                 add_header X-Robots-Tag "noindex, nofollow";
>                 proxy_pass http://127.0.0.1:3552;
>                 proxy_set_header X-Real-IP $remote_addr;
>         }
>         access_log /var/log/nginx/arcane-access.log;
>         error_log /var/log/nginx/arcane-error.log debug;
> }
> Any ideas? did you fellas do something besides upgrade?
> 
> Thanks!

I did not have websocket support enabled in my nginx options for arcane as it was working before without it. make sure to enable it

**Comment by patillacode** [comment]
Ty @jetlifedza, that was it.

For anyone that stumbles upon this thread [here](https://websocket.org/guides/infrastructure/nginx/) is how to set your nginx config with websockets enabled.

**Comment by kmendell** [comment]
I can add some notes to the docs, unless one of you would like to make a small PR on the website repo for this. Eitherway works.

**Comment by patillacode** [comment]
Sure, I'll add it.

@kmendell After a quick look I am not sure where the documentation is, can you point me to the files where I should add this to?

**Comment by kmendell** [comment]
https://github.com/ofkm/arcane-website
